name: LavaFurnace
version: ${project.version}
main: com.poweringg.lavaFurnace.LavaFurnace
description: Furnaces, smokers, and blast furnaces that burn infinitely without any fuel. Just place fire or a bucket of lava next to them!
author: Poweringg
website: https://github.com/Poweringg/LavaFurnace
api-version: '1.21'
commands:
  lavafurnace:
    description: Main command for LavaFurnace plugin
    usage: /lavafurnace [reload]
    permission: lavafurnace.admin
permissions:
  lavafurnace.use.*:
    description: Access to all lava furnace types
    children:
      lavafurnace.use.furnace: true
      lavafurnace.use.blast: true
      lavafurnace.use.smoker: true
  lavafurnace.use.furnace:
    description: Use normal furnace ignition
    default: true
  lavafurnace.use.blast:
    description: Use blast furnace ignition
    default: false
  lavafurnace.use.smoker:
    description: Use smoker ignition
    default: false